[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[window]
opacity = 0.85

[window.padding]
x = 8
y = 5

[keyboard]
bindings = [
   { key = "Return", mods = "Shift", action = "SpawnNewInstance" }
]
